/* eslint-disable no-undef */
const filterFormInputs = $.merge($('form select'), $('form input'));
const advancedFilterElementsId = [
  'loan_search_pool_id',
  'loan_search_innpact_loan_id',
  'loan_search_institution_group_id',
  'loan_search_country_group_id',
  'loan_search_currency_id',
  'loan_search_loan_type_id',
  'loan_search_proposed_nominal_amount_begin',
  'loan_search_proposed_nominal_amount_end',
  'loan_search_proposed_tenor_begin',
  'loan_search_proposed_tenor_end',
  'loan_search_proposed_spread_begin',
  'loan_search_proposed_spread_end',
  'loan_search_proposed_upfront_fees_begin',
  'loan_search_proposed_upfront_fees_end',
  'loan_search_proposed_fixed_rate_begin',
  'loan_search_proposed_fixed_rate_end',
  'loan_search_ratified_nominal_amount_begin',
  'loan_search_ratified_nominal_amount_end',
  'loan_search_ratified_tenor_begin',
  'loan_search_ratified_tenor_end',
  'loan_search_ratified_spread_begin',
  'loan_search_ratified_spread_end',
  'loan_search_ratified_upfront_fees_begin',
  'loan_search_ratified_upfront_fees_end',
  'loan_search_ratified_fixed_rate_begin',
  'loan_search_ratified_fixed_rate_end',
  'loan_search_approved_nominal_amount_begin',
  'loan_search_approved_nominal_amount_end',
  'loan_search_approved_tenor_begin',
  'loan_search_approved_tenor_end',
  'loan_search_approved_spread_begin',
  'loan_search_approved_spread_end',
  'loan_search_approved_upfront_fees_begin',
  'loan_search_approved_upfront_fees_end',
  'loan_search_approved_fixed_rate_begin',
  'loan_search_approved_fixed_rate_end',
  'loan_search_assignment_date_begin',
  'loan_search_assignment_date_end',
  'loan_search_deadline_assignment_date_begin',
  'loan_search_deadline_assignment_date_end',
  'loan_search_ratification_date_begin',
  'loan_search_ratification_date_end',
  'loan_search_deadline_ratification_date_begin',
  'loan_search_deadline_ratification_date_end',
  'loan_search_approval_date_begin',
  'loan_search_approval_date_end',
  'loan_search_deadline_approval_date_begin',
  'loan_search_deadline_approval_date_end',
  'loan_search_expected_disbursement_date_begin',
  'loan_search_expected_disbursement_date_end',
  'loan_search_specific_approval_condition',
  'loan_search_probabilities_begin',
  'loan_search_probabilities_end',
  'loan_search_institution_type_id',
  'loan_search_repayment_type_id',
  'loan_search_noval',
  'loan_search_executed_nominal_amount_begin',
  'loan_search_executed_nominal_amount_end',
  'loan_search_executed_tenor_begin',
  'loan_search_executed_tenor_end',
  'loan_search_loan_spread_begin',
  'loan_search_loan_spread_end',
  'loan_search_executed_upfront_fees_begin',
  'loan_search_executed_upfront_fees_end',
  'loan_search_executed_fixed_rate_begin',
  'loan_search_executed_fixed_rate_end',
  'loan_search_disbursement_date_begin',
  'loan_search_disbursement_date_end',
  'loan_search_maturity_date_begin',
  'loan_search_maturity_date_end',
  'loan_search_vrr_maturity_date_begin',
  'loan_search_vrr_maturity_date_end',
  'loan_search_provision_date_begin',
  'loan_search_provision_date_end',
  'loan_search_nav_usd_begin',
  'loan_search_nav_usd_end',
  'loan_search_net_position_value_begin',
  'loan_search_net_position_value_end',
  'loan_search_gross_position_value_begin',
  'loan_search_gross_position_value_end',
  'loan_search_critical_cases',
  'loan_search_loan_interest_rate_type_id',
  'loan_search_executed_bond_id',

];
const advancedFiltersNotEmpty = filterFormInputs.filter((index, element) => (advancedFilterElementsId.includes(element.id) && $(element).val !== undefined && $(element).val() !== ''));

if (advancedFiltersNotEmpty.length > 0) {
  $('.accordion-item').addClass('is-active');
  $('.accordion-content').attr('aria-hidden', false);
  $('.accordion-content').attr('style', 'display: block;');
}

$('.countries_list').select2();
