ALTER TABLE currencies
    ADD
      SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
        DEFAULT SYSUTCDATETIME()
    , SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
        DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime);

ALTER TABLE currencies
    SET (SYSTEM_VERSIONING = ON);

ALTER TABLE currency_countries
	ADD
    SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
        DEFAULT SYSUTCDATETIME()
    , SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
        DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime);

ALTER TABLE currency_countries
    SET (SYSTEM_VERSIONING = ON);

ALTER TABLE currency_rates
	ADD
    SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
        DEFAULT SYSUTCDATETIME()
    , SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
        DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime);

ALTER TABLE currency_rates
    SET (SYSTEM_VERSIONING = ON);