class ChangeInstitutionVariableNamesToBeDeleted < ActiveRecord::Migration[6.0]
  def up
    rename_column :institutions, :rural_borrowers_count, :rural_borrowers_count_to_be_deleted
    rename_column :institutions, :internal_rating, :internal_rating_to_be_deleted
    rename_column :institutions, :external_rating, :external_rating_to_be_deleted
    rename_column :institutions, :ia_esg_rating, :ia_esg_rating_to_be_deleted
    rename_column :institutions, :environmental_rating, :environmental_rating_to_be_deleted
    rename_column :institutions, :kyc_check, :kyc_check_to_be_deleted
    rename_column :institutions, :involvement_in_responsible_finance_initiatives, :involvement_in_responsible_finance_initiatives_to_be_deleted
    rename_column :institutions, :training_on_responsible_finance_targeting_women, :training_on_responsible_finance_targeting_women_to_be_deleted
    rename_column :institutions, :provision_of_financial_products_targeting_enterprise_set_up, :provision_of_financial_products_targeting_enterprise_set_up_to_be_deleted
    rename_column :institutions, :domestic_liabilities, :domestic_liabilities_to_be_deleted
    rename_column :institutions, :international_liabilities, :international_liabilities_to_be_deleted
    rename_column :institutions, :calendar_liabilities_and_assets, :calendar_liabilities_and_assets_to_be_deleted
    rename_column :institutions, :revenues, :revenues_to_be_deleted
    rename_column :institutions, :net_income_distributed_as_dividends, :net_income_distributed_as_dividends_to_be_deleted
    rename_column :institutions, :provision_for_loss, :provision_for_loss_to_be_deleted
    rename_column :institutions, :write_off, :write_off_to_be_deleted
    rename_column :institutions, :deposit_amount, :deposit_amount_to_be_deleted
    rename_column :institutions, :saving, :saving_to_be_deleted
    rename_column :institutions, :saving_amount, :saving_amount_to_be_deleted
    rename_column :institutions, :mobile_banking_services, :mobile_banking_services_to_be_deleted
    rename_column :institutions, :list_dfi_lenders, :list_dfi_lenders_to_be_deleted
    rename_column :institutions, :financial_strength_of_shareholders, :financial_strength_of_shareholders_to_be_deleted
    rename_column :institutions, :number_of_micro_borrowers, :number_of_micro_borrowers_to_be_deleted
    rename_column :institutions, :number_of_sme_borrowers, :number_of_sme_borrowers_to_be_deleted
    rename_column :institutions, :services, :services_to_be_deleted
    rename_column :institutions, :production, :production_to_be_deleted
    rename_column :institutions, :microenterprise_usd, :microenterprise_usd_to_be_deleted
    rename_column :institutions, :sme_usd, :sme_usd_to_be_deleted
    rename_column :institutions, :corporate_usd, :corporate_usd_to_be_deleted
    rename_column :institutions, :housing_usd, :housing_usd_to_be_deleted
    rename_column :institutions, :personal_usd, :personal_usd_to_be_deleted
    rename_column :institutions, :other_usd, :other_usd_to_be_deleted
    rename_column :institutions, :has_sptf_alinus_reporting_using_alinus, :has_sptf_alinus_reporting_using_alinus_to_be_deleted
    rename_column :institutions, :sptf_alinus_reporting_using_alinus, :sptf_alinus_reporting_using_alinus_to_be_deleted
    rename_column :institutions, :overall_sptf_alinus_score, :overall_sptf_alinus_score_to_be_deleted
    rename_column :institutions, :define_and_monitor_social_goals, :define_and_monitor_social_goals_to_be_deleted
    rename_column :institutions, :ensure_commitment_to_social_goals, :ensure_commitment_to_social_goals_to_be_deleted
    rename_column :institutions, :product_design_to_meet_clients_need, :product_design_to_meet_clients_need_to_be_deleted
    rename_column :institutions, :treat_clients_responsibly, :treat_clients_responsibly_to_be_deleted
    rename_column :institutions, :treat_employees_responsibly, :treat_employees_responsibly_to_be_deleted
    rename_column :institutions, :balance_financial_and_performance, :balance_financial_and_performance_to_be_deleted
    rename_column :institutions, :promote_environmental_protection, :promote_environmental_protection_to_be_deleted
    rename_column :institutions, :trade, :trade_to_be_deleted
    rename_column :institutions, :agriculture, :agriculture_to_be_deleted
    rename_column :institutions, :education, :education_to_be_deleted
    rename_column :institutions, :housing, :housing_to_be_deleted
    rename_column :institutions, :consumption, :consumption_to_be_deleted
    rename_column :institutions, :other, :other_to_be_deleted
    rename_column :institutions, :portfolio_3y_ago, :portfolio_3y_ago_to_be_deleted
    rename_column :institutions, :other_liabilities, :other_liabilities_to_be_deleted
    rename_column :institutions, :deposits, :deposits_to_be_deleted
    rename_column :institutions, :portfolio_breakdown_ii_as_of_date, :portfolio_breakdown_ii_as_of_date_to_be_deleted
    rename_column :institutions, :portfolio_breakdown_iii_as_of_date, :portfolio_breakdown_iii_as_of_date_to_be_deleted
    rename_column :institutions, :aptf_alinus_results_as_of_date, :aptf_alinus_results_as_of_date_to_be_deleted
    rename_column :institutions, :external_rating_agency, :external_rating_agency_to_be_deleted
    rename_column :institutions, :npls, :npls_to_be_deleted
    rename_column :institutions, :internal_impact_score, :internal_impact_score_to_be_deleted
    rename_column :institutions, :number_of_clients, :number_of_clients_to_be_deleted
    rename_column :institutions, :mobile_banking_percentage, :mobile_banking_percentage_to_be_deleted
    rename_column :institutions, :trade_and_services, :trade_and_services_to_be_deleted
    rename_column :institutions, :probability_of_default, :probability_of_default_to_be_deleted
    rename_column :institutions, :sme_portfolio_size_under_50k, :sme_portfolio_size_under_50k_to_be_deleted
    rename_column :institutions, :percentage_rural_ptf, :percentage_rural_ptf_to_be_deleted
    rename_column :institutions, :percentage_of_women_ptf, :percentage_of_women_ptf_to_be_deleted
    rename_column :institutions, :voluntary_savings, :voluntary_savings_to_be_deleted
    rename_column :institutions, :number_clients_using_mobile_banking, :number_clients_using_mobile_banking_to_be_deleted
    rename_column :institutions, :number_clients_with_deposits, :number_clients_with_deposits_to_be_deleted
    rename_column :institutions, :services_offered_as_of_date, :services_offered_as_of_date_to_be_deleted
    rename_column :institutions, :general_rating_as_of_date, :general_rating_as_of_date_to_be_deleted
    rename_column :institutions, :internal_credit_risk_rating, :internal_credit_risk_rating_to_be_deleted
  end

  def down
    rename_column :institutions, :rural_borrowers_count_to_be_deleted, :rural_borrowers_count
    rename_column :institutions, :internal_rating_to_be_deleted, :internal_rating
    rename_column :institutions, :external_rating_to_be_deleted, :external_rating
    rename_column :institutions, :ia_esg_rating_to_be_deleted, :ia_esg_rating
    rename_column :institutions, :environmental_rating_to_be_deleted, :environmental_rating
    rename_column :institutions, :kyc_check_to_be_deleted, :kyc_check
    rename_column :institutions, :involvement_in_responsible_finance_initiatives_to_be_deleted, :involvement_in_responsible_finance_initiatives
    rename_column :institutions, :training_on_responsible_finance_targeting_women_to_be_deleted, :training_on_responsible_finance_targeting_women
    rename_column :institutions, :provision_of_financial_products_targeting_enterprise_set_up_to_be_deleted, :provision_of_financial_products_targeting_enterprise_set_up
    rename_column :institutions, :domestic_liabilities_to_be_deleted, :domestic_liabilities
    rename_column :institutions, :international_liabilities_to_be_deleted, :international_liabilities
    rename_column :institutions, :calendar_liabilities_and_assets_to_be_deleted, :calendar_liabilities_and_assets
    rename_column :institutions, :revenues_to_be_deleted, :revenues
    rename_column :institutions, :net_income_distributed_as_dividends_to_be_deleted, :net_income_distributed_as_dividends
    rename_column :institutions, :provision_for_loss_to_be_deleted, :provision_for_loss
    rename_column :institutions, :write_off_to_be_deleted, :write_off
    rename_column :institutions, :deposit_amount_to_be_deleted, :deposit_amount
    rename_column :institutions, :saving_to_be_deleted, :saving
    rename_column :institutions, :saving_amount_to_be_deleted, :saving_amount
    rename_column :institutions, :mobile_banking_services_to_be_deleted, :mobile_banking_services
    rename_column :institutions, :list_dfi_lenders_to_be_deleted, :list_dfi_lenders
    rename_column :institutions, :financial_strength_of_shareholders_to_be_deleted, :financial_strength_of_shareholders
    rename_column :institutions, :number_of_micro_borrowers_to_be_deleted, :number_of_micro_borrowers
    rename_column :institutions, :number_of_sme_borrowers_to_be_deleted, :number_of_sme_borrowers
    rename_column :institutions, :services_to_be_deleted, :services
    rename_column :institutions, :production_to_be_deleted, :production
    rename_column :institutions, :microenterprise_usd_to_be_deleted, :microenterprise_usd
    rename_column :institutions, :sme_usd_to_be_deleted, :sme_usd
    rename_column :institutions, :corporate_usd_to_be_deleted, :corporate_usd
    rename_column :institutions, :housing_usd_to_be_deleted, :housing_usd
    rename_column :institutions, :personal_usd_to_be_deleted, :personal_usd
    rename_column :institutions, :other_usd_to_be_deleted, :other_usd
    rename_column :institutions, :has_sptf_alinus_reporting_using_alinus_to_be_deleted, :has_sptf_alinus_reporting_using_alinus
    rename_column :institutions, :sptf_alinus_reporting_using_alinus_to_be_deleted, :sptf_alinus_reporting_using_alinus
    rename_column :institutions, :overall_sptf_alinus_score_to_be_deleted, :overall_sptf_alinus_score
    rename_column :institutions, :define_and_monitor_social_goals_to_be_deleted, :define_and_monitor_social_goals
    rename_column :institutions, :ensure_commitment_to_social_goals_to_be_deleted, :ensure_commitment_to_social_goals
    rename_column :institutions, :product_design_to_meet_clients_need_to_be_deleted, :product_design_to_meet_clients_need
    rename_column :institutions, :treat_clients_responsibly_to_be_deleted, :treat_clients_responsibly
    rename_column :institutions, :treat_employees_responsibly_to_be_deleted, :treat_employees_responsibly
    rename_column :institutions, :balance_financial_and_performance_to_be_deleted, :balance_financial_and_performance
    rename_column :institutions, :promote_environmental_protection_to_be_deleted, :promote_environmental_protection
    rename_column :institutions, :trade_to_be_deleted, :trade
    rename_column :institutions, :agriculture_to_be_deleted, :agriculture
    rename_column :institutions, :education_to_be_deleted, :education
    rename_column :institutions, :housing_to_be_deleted, :housing
    rename_column :institutions, :consumption_to_be_deleted, :consumption
    rename_column :institutions, :other_to_be_deleted, :other
    rename_column :institutions, :portfolio_3y_ago_to_be_deleted, :portfolio_3y_ago
    rename_column :institutions, :other_liabilities_to_be_deleted, :other_liabilities
    rename_column :institutions, :deposits_to_be_deleted, :deposits
    rename_column :institutions, :portfolio_breakdown_ii_as_of_date_to_be_deleted, :portfolio_breakdown_ii_as_of_date
    rename_column :institutions, :portfolio_breakdown_iii_as_of_date_to_be_deleted, :portfolio_breakdown_iii_as_of_date
    rename_column :institutions, :aptf_alinus_results_as_of_date_to_be_deleted, :aptf_alinus_results_as_of_date
    rename_column :institutions, :external_rating_agency_to_be_deleted, :external_rating_agency
    rename_column :institutions, :npls_to_be_deleted, :npls
    rename_column :institutions, :internal_impact_score_to_be_deleted, :internal_impact_score
    rename_column :institutions, :number_of_clients_to_be_deleted, :number_of_clients
    rename_column :institutions, :mobile_banking_percentage_to_be_deleted, :mobile_banking_percentage
    rename_column :institutions, :trade_and_services_to_be_deleted, :trade_and_services
    rename_column :institutions, :probability_of_default_to_be_deleted, :probability_of_default
    rename_column :institutions, :sme_portfolio_size_under_50k_to_be_deleted, :sme_portfolio_size_under_50k
    rename_column :institutions, :percentage_rural_ptf_to_be_deleted, :percentage_rural_ptf
    rename_column :institutions, :percentage_of_women_ptf_to_be_deleted, :percentage_of_women_ptf
    rename_column :institutions, :voluntary_savings_to_be_deleted, :voluntary_savings
    rename_column :institutions, :number_clients_using_mobile_banking_to_be_deleted, :number_clients_using_mobile_banking
    rename_column :institutions, :number_clients_with_deposits_to_be_deleted, :number_clients_with_deposits
    rename_column :institutions, :services_offered_as_of_date_to_be_deleted, :services_offered_as_of_date
    rename_column :institutions, :general_rating_as_of_date_to_be_deleted, :general_rating_as_of_date
    rename_column :institutions, :internal_credit_risk_rating_to_be_deleted, :internal_credit_risk_rating
  end
end
